## File Name: RcppExports.R
## File Version: 0.26
# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenvaluesDsirt <- function(Xr, D, maxit, conv) {
    .Call('_sirt_eigenvaluesDsirt', PACKAGE = 'sirt', Xr, D, maxit, conv)
}

firsteigenvalsirt2 <- function(X, maxit, conv, K) {
    .Call('_sirt_firsteigenvalsirt2', PACKAGE = 'sirt', X, maxit, conv, K)
}

parameters_jackknife <- function(PARS) {
    .Call('_sirt_parameters_jackknife', PACKAGE = 'sirt', PARS)
}

evm_aux <- function(B, I, powD, maxit, conv, K) {
    .Call('_sirt_evm_aux', PACKAGE = 'sirt', B, I, powD, maxit, conv, K)
}

choppin_rowaveraging <- function(B, I, priorweight) {
    .Call('_sirt_choppin_rowaveraging', PACKAGE = 'sirt', B, I, priorweight)
}

evm_comp_matrix_poly <- function(dat, dat_resp, weights, JJ, jackunits, powD, progress_, row_index, col_index) {
    .Call('_sirt_evm_comp_matrix_poly', PACKAGE = 'sirt', dat, dat_resp, weights, JJ, jackunits, powD, progress_, row_index, col_index)
}

gooijer_csn_table <- function(dat, dat_perm, RR, NS, progress, progress_vec, score_index) {
    .Call('_sirt_gooijer_csn_table', PACKAGE = 'sirt', dat, dat_perm, RR, NS, progress, progress_vec, score_index)
}

isop_tests_C <- function(dat, dat_resp, weights, jackunits, JJ) {
    .Call('_sirt_isop_tests_C', PACKAGE = 'sirt', dat, dat_resp, weights, jackunits, JJ)
}

ia_optim_lambda <- function(lambda, psi0, psi0b, align_scale, align_pow, wgt, eps, group_combis) {
    .Call('_sirt_ia_optim_lambda', PACKAGE = 'sirt', lambda, psi0, psi0b, align_scale, align_pow, wgt, eps, group_combis)
}

ia_optim_nu <- function(lambda, nu, psi0_, psi0b, alpha0, alpha0b, align_scale, align_pow, wgt, eps, group_combis) {
    .Call('_sirt_ia_optim_nu', PACKAGE = 'sirt', lambda, nu, psi0_, psi0b, alpha0, alpha0b, align_scale, align_pow, wgt, eps, group_combis)
}

interval_index_C <- function(MATR, RN) {
    .Call('_sirt_interval_index_C', PACKAGE = 'sirt', MATR, RN)
}

rowCumsums2_source <- function(input) {
    .Call('_sirt_rowCumsums2_source', PACKAGE = 'sirt', input)
}

rowKSmallest_C <- function(MATR, KK1, INDEXMATR, RNMATR) {
    .Call('_sirt_rowKSmallest_C', PACKAGE = 'sirt', MATR, KK1, INDEXMATR, RNMATR)
}

rowMaxsCPP_source <- function(MATR) {
    .Call('_sirt_rowMaxsCPP_source', PACKAGE = 'sirt', MATR)
}

rowmins2_bundle_C <- function(m1, v1) {
    .Call('_sirt_rowmins2_bundle_C', PACKAGE = 'sirt', m1, v1)
}

calc_copula_itemcluster_C <- function(DD, res) {
    .Call('_sirt_calc_copula_itemcluster_C', PACKAGE = 'sirt', DD, res)
}

md_pattern_csource <- function(dat) {
    .Call('_sirt_md_pattern_csource', PACKAGE = 'sirt', dat)
}

monoreg_rowwise_Cpp <- function(YM, WM) {
    .Call('_sirt_monoreg_rowwise_Cpp', PACKAGE = 'sirt', YM, WM)
}

mle_pcm_group_C <- function(dat, dat_resp, groupM, b, a, maxK, theta0, conv, maxiter) {
    .Call('_sirt_mle_pcm_group_C', PACKAGE = 'sirt', dat, dat_resp, groupM, b, a, maxK, theta0, conv, maxiter)
}

mle_pcm_C <- function(dat, dat_resp, b, a, maxK, theta0, conv, maxiter) {
    .Call('_sirt_mle_pcm_C', PACKAGE = 'sirt', dat, dat_resp, b, a, maxK, theta0, conv, maxiter)
}

noharm_compute_dj <- function(Fval, Pval, I, D) {
    .Call('_sirt_noharm_compute_dj', PACKAGE = 'sirt', Fval, Pval, I, D)
}

noharm_compute_ej <- function(dj, I) {
    .Call('_sirt_noharm_compute_ej', PACKAGE = 'sirt', dj, I)
}

noharm_compute_vjk <- function(b0jk, b1jk, b2jk, b3jk, ej_ek, I, modtype) {
    .Call('_sirt_noharm_compute_vjk', PACKAGE = 'sirt', b0jk, b1jk, b2jk, b3jk, ej_ek, I, modtype)
}

noharm_compute_gammajk <- function(Fval, Pval, Psival, I, D) {
    .Call('_sirt_noharm_compute_gammajk', PACKAGE = 'sirt', Fval, Pval, Psival, I, D)
}

noharm_compute_pdfk <- function(Fval, Pval, I, D) {
    .Call('_sirt_noharm_compute_pdfk', PACKAGE = 'sirt', Fval, Pval, I, D)
}

noharm_estFcpp <- function(Fval, Pval, Fpatt, Ppatt, I, D, b0jk, b1jk, b2jk, b3jk, wgtm, pm, Psival, Psipatt, maxincrement, modtype) {
    .Call('_sirt_noharm_estFcpp', PACKAGE = 'sirt', Fval, Pval, Fpatt, Ppatt, I, D, b0jk, b1jk, b2jk, b3jk, wgtm, pm, Psival, Psipatt, maxincrement, modtype)
}

noharm_estPcpp <- function(Fval, Pval, Fpatt, Ppatt, I, D, b0jk, b1jk, b2jk, b3jk, wgtm, pm, Psival, Psipatt, maxincrement, modtype) {
    .Call('_sirt_noharm_estPcpp', PACKAGE = 'sirt', Fval, Pval, Fpatt, Ppatt, I, D, b0jk, b1jk, b2jk, b3jk, wgtm, pm, Psival, Psipatt, maxincrement, modtype)
}

noharm_estPsicpp <- function(Fval, Pval, Fpatt, Ppatt, I, D, b0jk, b1jk, b2jk, b3jk, wgtm, pm, Psival, Psipatt, maxincrement, modtype) {
    .Call('_sirt_noharm_estPsicpp', PACKAGE = 'sirt', Fval, Pval, Fpatt, Ppatt, I, D, b0jk, b1jk, b2jk, b3jk, wgtm, pm, Psival, Psipatt, maxincrement, modtype)
}

pbivnorm2_rcpp <- function(x_, y_, rho_) {
    .Call('_sirt_pbivnorm2_rcpp', PACKAGE = 'sirt', x_, y_, rho_)
}

dmvnorm_2dim_rcpp <- function(x_, y_, rho_) {
    .Call('_sirt_dmvnorm_2dim_rcpp', PACKAGE = 'sirt', x_, y_, rho_)
}

polychoric2_estequation <- function(frtab, maxK, rho, thresh1n, thresh2n, maxK1, maxK2) {
    .Call('_sirt_polychoric2_estequation', PACKAGE = 'sirt', frtab, maxK, rho, thresh1n, thresh2n, maxK1, maxK2)
}

polychoric2_itempair <- function(v1, v2, maxK, maxiter) {
    .Call('_sirt_polychoric2_itempair', PACKAGE = 'sirt', v1, v2, maxK, maxiter)
}

tetrachoric2_rcpp_aux <- function(dfr, numdiffparm, maxiter) {
    .Call('_sirt_tetrachoric2_rcpp_aux', PACKAGE = 'sirt', dfr, numdiffparm, maxiter)
}

polychoric2_aux_rcpp <- function(dat, maxK, maxiter) {
    .Call('_sirt_polychoric2_aux_rcpp', PACKAGE = 'sirt', dat, maxK, maxiter)
}

probs_pcm_groups_C <- function(dat, dat_resp, group, probs, CC, TP) {
    .Call('_sirt_probs_pcm_groups_C', PACKAGE = 'sirt', dat, dat_resp, group, probs, CC, TP)
}

probs_pcm_nogroups_C <- function(dat, dat_resp, probs, CC, TP) {
    .Call('_sirt_probs_pcm_nogroups_C', PACKAGE = 'sirt', dat, dat_resp, probs, CC, TP)
}

calccounts_pcm_groups_C <- function(dat, dat_resp, group, fyiqk, pik, CC, weights) {
    .Call('_sirt_calccounts_pcm_groups_C', PACKAGE = 'sirt', dat, dat_resp, group, fyiqk, pik, CC, weights)
}

rm_proc_datasets_na_indicators <- function(dat, K) {
    .Call('_sirt_rm_proc_datasets_na_indicators', PACKAGE = 'sirt', dat, K)
}

rm_proc_expand_dataset <- function(dat, rater0, pid0, N, R) {
    .Call('_sirt_rm_proc_expand_dataset', PACKAGE = 'sirt', dat, rater0, pid0, N, R)
}

rm_arraymult1 <- function(AA, dimAA, BB, dimBB) {
    .Call('_sirt_rm_arraymult1', PACKAGE = 'sirt', AA, dimAA, BB, dimBB)
}

RM_CALCPOST <- function(DAT2, DAT2RESP, PROBS, KK) {
    .Call('_sirt_RM_CALCPOST', PACKAGE = 'sirt', DAT2, DAT2RESP, PROBS, KK)
}

rm_probraterfct1 <- function(CRA, DRA, dimAA, BB, dimBB) {
    .Call('_sirt_rm_probraterfct1', PACKAGE = 'sirt', CRA, DRA, dimAA, BB, dimBB)
}

rm_facets_calcprobs_cpp <- function(b_item, b_rater, Qmatrix, tau_item, K, I, TP, a_item, a_rater, item_index, rater_index, theta_k) {
    .Call('_sirt_rm_facets_calcprobs_cpp', PACKAGE = 'sirt', b_item, b_rater, Qmatrix, tau_item, K, I, TP, a_item, a_rater, item_index, rater_index, theta_k)
}

SMIRT_CALCPOST <- function(DAT2, DAT2RESP, PROBS, DAT2IND, PIK, KK1) {
    .Call('_sirt_SMIRT_CALCPOST', PACKAGE = 'sirt', DAT2, DAT2RESP, PROBS, DAT2IND, PIK, KK1)
}

SMIRT_CALCPROB_COMP <- function(A, B, QQ, THETA, CC, DD) {
    .Call('_sirt_SMIRT_CALCPROB_COMP', PACKAGE = 'sirt', A, B, QQ, THETA, CC, DD)
}

SMIRT_CALCPROB_NONCOMP <- function(A, B, QQ, THETA, CC, DD) {
    .Call('_sirt_SMIRT_CALCPROB_NONCOMP', PACKAGE = 'sirt', A, B, QQ, THETA, CC, DD)
}

SMIRT_CALCPROB_PARTCOMP <- function(A, B, QQ, THETA, CC, DD, MUI) {
    .Call('_sirt_SMIRT_CALCPROB_PARTCOMP', PACKAGE = 'sirt', A, B, QQ, THETA, CC, DD, MUI)
}

MML2_RASCHTYPE_COUNTS <- function(DAT2, DAT2RESP, DAT1, FQKYI, PIK, FYIQK) {
    .Call('_sirt_MML2_RASCHTYPE_COUNTS', PACKAGE = 'sirt', DAT2, DAT2RESP, DAT1, FQKYI, PIK, FYIQK)
}

MML2_CALCPOST_V1 <- function(DAT2, DAT2RESP, PROBS) {
    .Call('_sirt_MML2_CALCPOST_V1', PACKAGE = 'sirt', DAT2, DAT2RESP, PROBS)
}

MML2_CALCPOST_V2 <- function(DAT2, DAT2RESP, PROBS) {
    .Call('_sirt_MML2_CALCPOST_V2', PACKAGE = 'sirt', DAT2, DAT2RESP, PROBS)
}

MML2_CALCPOST_V3 <- function(DAT2, DAT2RESP, PROBS) {
    .Call('_sirt_MML2_CALCPOST_V3', PACKAGE = 'sirt', DAT2, DAT2RESP, PROBS)
}

sirt_rcpp_xxirt_compute_posterior_expected_counts <- function(dat1_resp_gg, p_aj_xi_gg) {
    .Call('_sirt_sirt_rcpp_xxirt_compute_posterior_expected_counts', PACKAGE = 'sirt', dat1_resp_gg, p_aj_xi_gg)
}

sirt_rcpp_xxirt_compute_likelihood <- function(dat, dat_resp_bool, probs, TP, maxK) {
    .Call('_sirt_sirt_rcpp_xxirt_compute_likelihood', PACKAGE = 'sirt', dat, dat_resp_bool, probs, TP, maxK)
}

